services:
  # SQLite 压力测试运行器 - 使用 SQLite 优化配置
  sqlite-test:
    build:
      context: .
      dockerfile: Dockerfile.cgo.integration
    container_name: batchsql-sqlite-test
    env_file:
      - .env.sqlite.test  # 使用 SQLite 专用配置
    environment:
      - SQLITE_DSN=/app/data/test.db
      - TEST_TYPE=sqlite
    volumes:
      - ./test/reports:/app/reports
      - ./test/data:/app/data
    networks:
      - batchsql-network
    command: ["./run-single-db-test.sh"]

volumes:
  sqlite_data:

networks:
  batchsql-network:
    driver: bridge