global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # BatchSQL集成测试监控
  - job_name: 'batchsql-integration-test'
    static_configs:
      - targets: ['integration-test:9091']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # 如果有其他BatchSQL应用实例，可以添加更多job
  # - job_name: 'batchsql-app'
  #   static_configs:
  #     - targets: ['app:9092']