name: Feature Request
description: Suggest a new feature for BatchSQL
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for BatchSQL!
        
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core Functionality
        - Database Driver
        - Performance Optimization
        - API Enhancement
        - Testing & Quality
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...
    validations:
      required: false
      
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific use cases where this feature would be beneficial.
      placeholder: |
        1. When working with large datasets...
        2. In high-concurrency scenarios...
        3. For better error handling...
    validations:
      required: true
      
  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about how the API should look, please share them.
      render: go
      placeholder: |
        // Example API design
        batch := batchsql.NewBatchSQL(...)
        batch.NewFeature(...)
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
        - Critical - Essential for adoption
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Simple addition or modification
        - Medium - Moderate changes required
        - High - Significant architectural changes
        - Unknown - Not sure about implementation complexity
    validations:
      required: false
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to implement this feature myself
        - label: I can help with testing and feedback
        - label: I can help with documentation
        - label: I can provide use case examples
        
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided clear use cases for this feature
          required: true
        - label: I understand this is a feature request and not a bug report
          required: true